name: Windows build (x64)

on:
  workflow_dispatch: {}          # Actions → Run workflow থেকে হাতে চালানো যাবে
  push:
    branches: [ "main" ]         # main এ push হলেই চলবে

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust (stable MSVC)
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable-x86_64-pc-windows-msvc

      - name: Build (release)
        run: cargo build --release

      - name: Package artifact (.zip)
        shell: pwsh
        run: |
          New-Item -ItemType Directory -Force -Path dist | Out-Null
          Copy-Item target\release\webfigchecker.exe dist\
          if (Test-Path README.md) { Copy-Item README.md dist\ }
          Compress-Archive -Path dist\* -DestinationPath webfigchecker-windows-x64.zip -Force

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: webfigchecker-windows-x64
          path: webfigchecker-windows-x64.zip
